### ISSUE TITLE
add a script to the list

### ISSUE THREAD

**Issue by kulverstukas1** [evilpete/flipper_toolbox#10]
Hey, inspired by [nfc_hexdump.py](https://github.com/evilpete/flipper_toolbox/blob/main/nfc_hexdump.py) I wrote my own version: [nfc_dumpconvert.py](https://github.com/kulverstukas1/nfc_dumpconvert/blob/main/nfc_dumpconvert.py) which might find its place here, but I was unsure of how to add that to the list.

**Comment by evilpete** [comment]
> Hey, inspired by [nfc_hexdump.py](https://github.com/evilpete/flipper_toolbox/blob/main/nfc_hexdump.py) I wrote my own version: [nfc_dumpconvert.py](https://github.com/kulverstukas1/nfc_dumpconvert/blob/main/nfc_dumpconvert.py) which might find its place here, but I was unsure of how to add that to the list.

just submit pull request

**Comment by kulverstukas1** [comment]
Okay, PR added.
