### ISSUE TITLE
Convert rtl_433 .ook files to Flipper .sub

### ISSUE THREAD

**Issue by strasharo** [evilpete/flipper_toolbox#4]
Hello. Is there a way to convert the .ook files produced by rtl_433 to the Flipper .sub format?

Thank you!

**Comment by evilpete** [comment]
it's possible although .ook files does not store the RF freq (center_frequency) when reading from saved data.

I'll throw something together as a test.

**Comment by evilpete** [comment]
@strasharo  


 take a look at [ook_to_sub.py](https://github.com/evilpete/flipper_toolbox/blob/dev/ook_to_sub.py) in the [dev](https://github.com/evilpete/flipper_toolbox/tree/dev) branch) it still needs clean up and testing but should work
 
 Note that you will have to specify the frequency when converting  .ook files

**Comment by strasharo** [comment]
Thanks a lot, @evilpete , I'll try it. :)
