### ISSUE TITLE
NFC Url No Such File / Bad Interpreter error?

### ISSUE THREAD

**Issue by Az-Neter** [evilpete/flipper_toolbox#5]
[az@az-server Downloads]$ ls
nfc_gen_url.py

[az@az-server Downloads]$ ./nfc_gen_url.py https://google.com"Test" > Test.nfc

bash: ./nfc_gen_url.py: /usr/local/bin/python3: bad interpreter: No such file or directory

????????
Why does your script tell me I have no python files when comes default on 99% of linux systems?
I installed ndeflib already too...

**Comment by Az-Neter** [comment]
Oh, nevermind: You reference entirely the wrong location for the python libaries, which by default install under /bin, NOT /usr/local/bin
You should probably fix that.

**Comment by evilpete** [comment]
fixed [a4d1ea4](https://github.com/evilpete/flipper_toolbox/commit/a4d1ea4c7a31931e6502f16f039a326bf9d44b47)
