### ISSUE TITLE
Unable to properly time RAW files with subghz_ook_to_sub.py

### ISSUE THREAD

**Issue by Crsarmv7l** [evilpete/flipper_toolbox#6]
Hi Pete,

Great tools. Running into a bit of an issue when using subghz_ook_to_sub.py. I created a .cu8 file with a dummy signal before the actual signal with sox, I then convert to .ook with rtl_433, then use your python script to create the sub file. It appears when creating the sub my dummy signal is stripped out. Here is an example of the dummy signal:

dd bs=5000 count=1 if=/dev/zero | sox -t raw -v 0 -c2 -b8 -eunsigned-integer -r 250k - -t raw - > $HOME/______.cu8

I then cat the actual signal to that same file.

Without the dummy signal to buffer it is hard to get the timings right.

**Comment by evilpete** [comment]
Send me the ook file your having problems with. and I'll try to figure it out

It's admittedly the script a quick hack,

**Comment by evilpete** [comment]
Ahh..  @Crsarmv7l 

are wondering why your blank preface signal is not included in the final output?

rtl_433 only includes the demodulated data, thus it is not there when  the ook file is translated into a flipper sub file

**Comment by Crsarmv7l** [comment]
Thanks @evilpete
