### ISSUE TITLE
AttributeError: module 'ndef' has no attribute 'UriRecord'

### ISSUE THREAD

**Issue by DRA6N** [evilpete/flipper_toolbox#7]
when running the script I get this error:

```
  File "C:\Users\userr\Desktop\nfc_gen_url.py", line 134, in <module>
    nfc_data = gen_nfc_sub(arg_data)
  File "C:\Users\user\Desktop\nfc_gen_url.py", line 77, in gen_nfc_sub
    tag_message.append(ndef.UriRecord(x[1]))
AttributeError: module 'ndef' has no attribute 'UriRecord'
```

**Comment by evilpete** [comment]
@DRA6N  what command line args did you use ?

**Comment by DRA6N** [comment]
> @DRA6N what command line args did you use ?

python3 ./nfc_gen_url.py https://youtu.be/dQw4w9WgXcQ "Rick Roll" > rickroll.nfc

I found [Flipper Maker](https://flippermaker.github.io/) though which works well.

**Comment by evilpete** [comment]
@DRA6N 

on my systems I have [ndeflib 0.3.3](https://pypi.org/project/ndeflib/)  installed. 

> pip3 show ndeflib
```
Name: ndeflib
Version: 0.3.3
Summary: NFC Data Exchange Format decoder and encoder.
Home-page: https://ndeflib.readthedocs.io/
Author: Stephen Tiedemann
Author-email: stephen.tiedemann@gmail.com
License: ISC
Location: /usr/local/lib/python3.9/site-packages
Requires:
Required-by:


```

**Comment by DRA6N** [comment]
ah, there we go. I didn't realize that was what was missing. thanks!
